name: ffcache
description: ffcache is file based key value store
version: 0.1.0
author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/ffcache

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
